### ISSUE TITLE
Error when trying to block user

### ISSUE THREAD

**Issue by MakaryGo** [jaydenkieran/mw-discord#27]
```
[2ce78c058445ead74961222b] /Specjalna:Blokuj/CarmaRoof83 Error from line 210 of /.../wiki.mikronacje.info/mediawiki/extensions/Discord/src/DiscordHooks.php: Cannot access protected property MediaWiki\Block\DatabaseBlock::$mReason

Backtrace:

#0 /.../wiki.mikronacje.info/mediawiki/includes/HookContainer/HookContainer.php(320): DiscordHooks::onBlockIpComplete(MediaWiki\Block\DatabaseBlock, User, NULL)
#1 /.../wiki.mikronacje.info/mediawiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /.../wiki.mikronacje.info/mediawiki/includes/HookContainer/HookRunner.php(1078): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /.../wiki.mikronacje.info/mediawiki/includes/specials/SpecialBlock.php(1023): MediaWiki\HookContainer\HookRunner->onBlockIpComplete(MediaWiki\Block\DatabaseBlock, User, NULL)
#4 /.../wiki.mikronacje.info/mediawiki/includes/specials/SpecialBlock.php(1235): SpecialBlock::processForm(array, RequestContext)
#5 /.../wiki.mikronacje.info/mediawiki/includes/htmlform/HTMLForm.php(707): SpecialBlock->onSubmit(array, OOUIHTMLForm)
#6 /.../wiki.mikronacje.info/mediawiki/includes/htmlform/HTMLForm.php(597): HTMLForm->trySubmit()
#7 /.../wiki.mikronacje.info/mediawiki/includes/htmlform/HTMLForm.php(613): HTMLForm->tryAuthorizedSubmit()
#8 /.../wiki.mikronacje.info/mediawiki/includes/specialpage/FormSpecialPage.php(187): HTMLForm->show()
#9 /.../wiki.mikronacje.info/mediawiki/includes/specialpage/SpecialPage.php(600): FormSpecialPage->execute(string)
#10 /.../wiki.mikronacje.info/mediawiki/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(string)
#11 /.../wiki.mikronacje.info/mediawiki/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#12 /.../wiki.mikronacje.info/mediawiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#13 /.../wiki.mikronacje.info/mediawiki/includes/MediaWiki.php(543): MediaWiki->main()
#14 /.../wiki.mikronacje.info/mediawiki/index.php(53): MediaWiki->run()
#15 /.../wiki.mikronacje.info/mediawiki/index.php(46): wfIndexMain()
#16 {main}
```

**Comment by jaydenkieran** [comment]
What version of MediaWiki are you using?

**Comment by MakaryGo** [comment]
Currently 1.35.0-wmf.41

**Comment by orchardstreet** [comment]
Same issue on 1.35.0-rc.3 (534a693), latest Mediawiki REL1_35 commit, 9/14/20
Have to disable this Discord extension to block someone. Same backtrace as MakaryGo

**Comment by orchardstreet** [comment]
submitted pull request with the fix:
https://github.com/orchardstreet/mw-discord/commit/b3297ed60e8cd723f944dfb5bf20d1a6e21c8d90
'mReason' is deprecated in MW 1.35+, replaced with getReasonComment()->text
and included old code for lower versions with an if statement in the pull request
